version: "3.7"

services:

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password